<template>
    <div class="homepage-wrap">
        <div class="p-8 bg-white rounded-md mt-2xl">
            <div>
                <p align="center"><strong><strong>I. OP&Scaron;TE ODREDBE</strong></strong></p>
                <p align="center"><strong>Član 1.</strong><br /><strong>(Predmet uređenja)</strong></p>
                <p align="center">&nbsp;</p>
                <div align="justify"><br />(1) Ovim Zakonom uređuju se uslovi za obavljanje djelatnosti posredovanja u prometu&nbsp;<a href="https://advokat-prnjavorac.com/nekretnine-BiH.html">nekretnina</a>, prava i obaveze posrednika, agenata posredovanja i nalogodavaca u prometu nekretnina, op&scaron;ti uslovi poslovanja, sklapanje ugovora o posredovanju u prometu nekretnina, posrednička naknada, stručni ispit za obavljanje poslova agenta posredovanja u prometu nekretnina te nadzor nad primjenom ovog zakona.<br />(2) Na pitanja koja nisu posebno uređena ovim Zakonom,shodno se primjenjuju odredbe zakona kojim se uređuju obligacioni odnosi.</div>
                <p align="center"><br /><strong>Član 2.</strong><br /><strong>(Značenje izraza sadržanih u Zakonu)</strong></p>
                <div align="justify"><br />Pojedini izrazi u smislu ovoga Zakona imaju sljedeće značenje:<br />a) Posredovanje u prometu nekretnina (u daljnjem tekstu: posredovanje) je djelatnost koja obuhvata poslove pronalaženja i dovođenja u vezu nalogodavca i trećeg lica radi pregovora i pripreme za sklapanje pravnog posla čiji je predmet određena nekretnina prilikom kupovine, prodaje, zamjene i zakupa.<br />b) Posrednik u prometu nekretnina (u daljnjem tekstu:posrednik) je pravno ili fizičko lice, registrovano za obavljanje djelatnosti posredovanja koje ima sjedi&scaron;te ili podružnicu na području Federacije Bosne i Hercegovine (u daljnjem tekstu: Federacija BiH) i koje je upisano u Registar posrednika.<br />c) Registar posrednika je registar u koji se upisuju podaci o pravnim i fizičkim licima kojima je Federalno ministarstvo trgovine (u daljnjem tekstu: Ministarstvo) izdalo rje&scaron;enje o ispunjavanju uslova za obavljanje posredovanja u prometu nekretnina i upisu u Registar posrednika.<br />d) Agent posredovanja u prometu nekretnina (u daljnjem tekstu: agent posredovanja) je fizičko lice koje je položilo stručni ispit i upisano je u Imenik agenata posredovanja u prometu nekretnina.<br />e) Nekretnine su čestice zemlji&scaron;ne povr&scaron;ine, zajedno sa svime &scaron;to je sa zemlji&scaron;tem trajno spojeno na povr&scaron;ini ili ispod nje u skladu s odredbama zakona kojim se uređuju stvarna prava u Federaciji BiH.<br />f) Nalogodavac&nbsp;je fizičko ili pravno lice koje sa posrednikom zaključuje pisani ugovor o posredovanju.<br />g) Treće lice&nbsp;je lice koje posrednik nastoji dovesti u vezu sa nalogodavcem radi pregovora i pripreme za sklapanje pravnog posla čiji je predmet određena nekretnina prilikom kupovine, prodaje, zamjene i zakupa.</div>
                <p align="center"><br /><strong><strong>II. USLOVI ZA OBAVLJANJE POSREDOVANJA</strong></strong></p>
                <p align="center"><strong>Član 3.</strong><br /><strong>(Zabrana neovla&scaron;tenog obavljanja posredovanja)</strong></p>
                <div align="justify"><br />(1) Posredovanjem uz novčanu naknadu mogu se baviti samo posrednici iz člana 2. tačka b) ovog zakona koji ispunjavaju uslove propisane ovim zakonom.<br />(2) Zabranjeno je fizičkom licu obavljanje posredovanja uz novčanu naknadu suprotno odredbama ovog zakona.</div>
                <p align="center"><br /><strong>Član 4.</strong><br /><strong>(Uslovi za upis u Registar posrednika)</strong></p>
                <div align="justify"><br />U Registar posrednika može se upisati:<br />a) pravno lice registrovano za obavljanje djelatnosti posredovanja na osnovu upisa u Registar poslovnih subjekata u nadležnom općinskom sudu i fizičko lice registrovano za obavljanje djelatnosti posredovanja na osnovu rje&scaron;enja nadležnog gradskog, odnosno općinskog organa uprave,<br />b) ima sjedi&scaron;te ili podružnicu na području Federacije BiH,<br />c) ima zaposleno najmanje jedno lice koje ima položen stručni ispit iz člana 12. ovog zakona na puno radno vrijeme,<br />d) ima ugovor o osiguranju zaključen u skladu sa članom 5. ovog zakona,<br />e) ima odgovarajući poslovni prostor za obavljanje djelatnosti posredovanja u skladu sa ovim zakonom.</div>
                <p align="center"><br /><strong>Član 5.</strong><br /><strong>(Osiguranje od odgovornosti za &scaron;tetu)</strong></p>
                <div align="justify"><br />(1) Posrednik je dužan kod osiguravajućeg dru&scaron;tva u Bosni i Hercegovini osigurati se i obnavljati osiguranje od odgovornosti za &scaron;tetu koju bi nalogodavcu ili trećem licu mogao prouzrokovati obavljanjem posredovanja.<br />(2) Za &scaron;tetu koju bi posrednik mogao prouzrokovati obavljanjem posredovanja najniža osigurana svota ne može biti manja od 50.000,00 KM po jednom &scaron;tetnom događaju, odnosno 150.000,00 KM za sve od&scaron;tetne zahtjeve u jednoj osiguravajućoj godini.<br />(3) Posrednik za &scaron;tetu koju bi mogao prouzrokovati obavljanjem posredovanja odgovara po op&scaron;tim pravilima odgovornosti za naknadu &scaron;tete.</div>
                <p align="center"><br /><strong>Član 6.</strong><br /><strong>(Rje&scaron;enje o ispunjavanju uslova za obavljanje posredovanja i upis u Registar posrednika)</strong></p>
                <div align="justify"><br />(1) Rje&scaron;enje o ispunjavanju uslova za obavljanje posredovanja i upisu u Registar posrednika donosi Ministarstvo na zahtjev pravnog ili fizičkog lica, u roku od osam dana od dana prijema urednog zahtjeva.<br />(2) Posrednik može započeti obavljati djelatnost danom upisa u Registar posrednika.<br />(3) Posrednik koji je upisan u Registar posrednika dužan je jednom godi&scaron;nje, a najdalje do 31.marta tekuće godine, Ministarstvu dostaviti dokumentaciju iz koje se može utvrditi da nisu prestali postojati zakonski uslovi za obavljanje posredovanja.<br />(4) Ako Ministarstvo odbije zahtjev za izdavanje rje&scaron;enja iz stava (1) ovog člana, podnosilac zahtjeva može raskinuti ugovor iz člana 5. ovog zakona i tražiti povrat premije osiguranja.<br />(5) Protiv rje&scaron;enje iz stava (1) ovog člana žalba nije dozvoljena, ali se može tužbom pokrenuti upravni spor kod nadležnog suda.</div>
                <p align="center"><br /><strong>Član 7.</strong><br /><strong>(Registar posrednika)</strong></p>
                <div align="justify"><br />(1) Registar posrednika je registar koji u pisanoj i elektronskoj formi vodi Ministarstvo.<br />(2) Oblik, sadržaj i način vođenja Registra posrednika propisuje federalni ministar trgovine (u daljnjem tekstu: ministar).</div>
                <p align="center"><br /><strong>Član 8.</strong><br /><strong>(Javnost Registra posrednika)</strong></p>
                <div align="justify"><br />(1) Registar posrednika je javan i sva lica mogu besplatno vr&scaron;iti uvid u podatke koji se vode u Registru posrednika, bez ograničenja.<br />(2) Ministarstvo objavljuje Registar posrednika na internet stranici Ministarstva.</div>
                <p align="center"><br /><strong>Član 9.</strong><br /><strong>(Izvod iz Registra posrednika)</strong></p>
                <br />Na zahtjev zainteresovanog lica Ministarstvo izdaje izvod iz Registra posrednika, u roku od tri dana od dana prijema zahtjeva.
                <p align="center"><br /><strong>Član 10.</strong><br /><strong>(Promjena podataka u Registru posrednika)</strong></p>
                <div align="justify"><br />(1) Posrednik je dužan prijaviti svaku promjenu podataka koji se upisuju u Registar posrednika u roku od sedam dana od dana nastanka promjene, radi upisa promjene podataka u Registar posrednika.<br />(2) Ministarstvo vr&scaron;i promjenu podataka u Registru posrednika i po službenoj dužnosti na osnovu podataka iz službenih evidencija nadležnih organa, kao i podataka utvrđenih u postupku nadzora koji se provodi u skladu sa ovim zakonom.</div>
                <p align="center"><br /><strong>Član 11.</strong><br /><strong>(Brisanje iz Registra posrednika)</strong></p>
                <div align="justify"><br />(1) Posrednik se bri&scaron;e iz Registra posrednika rje&scaron;enjem Ministarstva u sljedećim slučajevima:<br />a) ako prestane da ispunjava neki od uslova iz člana 4. ovog zakona,<br />b) ako je posredniku pravosnažno izrečena za&scaron;titna mjera zabrane obavljanja djelatnosti, dok ta mjera traje,<br />c) na zahtjev posrednika.<br />(2) Rje&scaron;enje o brisanju iz Registra posrednika na osnovu stava (1) tač. a) i b) ovog člana Ministarstvo donosi po službenoj dužnosti na osnovu podataka iz službenih evidencija nadležnih organa, kao i podataka utvrđenih u postupku nadzora koji se provodi u skladu s ovim zakonom.<br />(3) Protiv rje&scaron;enje iz stava (1) ovog člana žalba nije dozvoljena, ali se može tužbom pokrenuti upravni spor kod nadležnog suda.</div>
                <p align="center"><br /><strong>Član 12.</strong><br /><strong>(Stručna osposobljenost)</strong></p>
                <div align="justify"><br />(1) Stručna osposobljenost za obavljanje poslova posredovanja utvrđuje se polaganjem stručnog ispita za posredovanje u prometu&nbsp;nekretnina (u daljnjem tekstu: stručni ispit).<br />(2) Fizičko lice koje polaže stručni ispit mora imati prebivali&scaron;te u Bosni i Hercegovini i najmanje IV stepen stručne spreme.</div>
                <p align="center"><br /><strong>Član 13.</strong><br /><strong>(Stručni ispit)</strong></p>
                <div align="justify"><br />(1) Stručni ispit provodi Privredna/Gospodarska komora Federacije Bosne i Hercegovine (u daljnjem tekstu:Komora) prema Programu osposobljavanja za agenta posredovanja u prometu nekretnina.<br />(2) Stručni ispit polaže se pred ispitnom komisijom koju za svaki ispitni rok s Liste ispitivača odlukom imenuje predsjednik Komore.<br />(3) Listu ispitivača rje&scaron;enjem imenuje ministar na prijedlog Komore i Ministarstva,na mandat od četiri godine, i to iz reda stručnjaka za područja ispitnih predmeta: privredna dru&scaron;tva i&nbsp;<a href="https://advokat-prnjavorac.com/Ugovor-o-kupoprodaji-nekretnina.html">ugovori</a>, stvarna prava na nekretninama i&nbsp;<a href="https://advokat-prnjavorac.com/zemljisne_knjige.html">zemlji&scaron;ne knjige</a>, porezi, finansijsko poslovanje, marketing, prostorno uređenje i gradnja.<br />(4) Fizičkom licu koje je položilo stručni ispit izdaje se uvjerenje o položenome stručnom ispitu. Komora vodi evidenciju fizičkih lica koja su položila stručni ispit<br />(5) Danom položenog stručnog ispita Komora vr&scaron;i upis lica iz stava (4) ovog člana u Imenik agenata posredovanja u prometu nekretnina (u daljnjem tekstu: Imenik agenata posredovanja).<br />(6) Oblik, sadržaj i način vođenja Imenika agenata posredovanja propisuje ministar.<br />(7) Program osposobljavanja za agenta posredovanja propisuje ministar na prijedlog Komore.<br />(8) Način i postupak provođenja stručnog ispita, sadržaj i oblik uvjerenja o položenome stručnom ispitu, oblik i način vođenja evidencije i visinu naknade tro&scaron;kova stručnog ispita, propisuje Komora uz saglasnost Ministarstva.<br />(9) Nadzor nad zakonito&scaron;ću organizacije i provođenja stručnog ispita vr&scaron;i Ministarstvo.</div>
                <p align="center"><br /><strong><strong>III. NAČIN OBAVLJANJA POSREDOVANJA</strong></strong></p>
                <p align="center"><strong>Član 14.</strong><br /><strong>(Zabrana neovla&scaron;tenog posredovanja i sukob interesa)</strong></p>
                <div align="justify"><br />(1) Djelatnost posredovanja može obavljati pravno ili fizičko lice koje je upisano u Registar posrednika.<br />(2) Poslove posredovanja kod posrednika ne može obavljati fizičko lice koje nije upisano u Imenik agenata posredovanja.<br />(3) Agent posredovanja ne smije bez pismene saglasnosti posrednika za kojeg na osnovu ugovora o radu obavlja poslove posredovanja obavljati istovremeno istovrsne ili slične poslove za drugog posrednika ili sebe lično.<br />(4) Ako agent posredovanja postupi protivno zabrani iz stava (3) ovoga člana, posrednik može od njega tražiti naknadu pretrpljene &scaron;tete ili može tražiti da se sklopljeni posao smatra sklopljenim za njegov račun, odnosno da mu agent posredovanja preda zaradu ostvarenu iz takvoga posla ili da na njega prenese potraživanje zarade iz takvoga posla.</div>
                <p align="center"><br /><strong>Član 15.</strong><br /><strong>(Ugovor o posredovanju)</strong></p>
                <div align="justify"><br />(1) Ugovorom o posredovanju obavezuje se posrednik da će nastojati naći i dovesti u vezu sa nalogodavcem treće lice radi pregovora za sklapanja pravnog posla čiji je predmet određena nekretnina, posebno pri kupovini, prodaji, zamjeni i zakupu, a nalogodavac se obavezuje da će mu isplatiti određenu posredničku naknadu ako taj pravni posao bude sklopljen.<br />(2) Ugovor o posredovanju zaključuje se u pisanom obliku i na određeno vrijeme.<br />(3) Zabranjeno je obavljanje poslova posredovanja bez zaključenog ugovora o posredovanju između posrednika i nalogodavca<br />(4) Ako ugovorne strane ne dogovore rok na koji sklapaju ugovor o posredovanju, smatra se da je ugovor o posredovanju sklopljen na određeno vrijeme od 12 mjeseci i može se sporazumom stranaka vi&scaron;e puta produžiti.<br />(5) Ako nije drukčije propisano ovim zakonom, na obavezni odnos između posrednika i nalogodavca primjenjuju se odredbe zakona kojim se uređuju obligacioni odnosi.<br />(6) Odredbe ovoga zakona ugovorom se ne mogu isključiti, odnosno ograničiti, osim ako je u vezi sa pojedinom odredbom izričito dopu&scaron;ten drugačiji dogovor ugovornih strana, odnosno drugačiji dogovor u očitome interesu nalogodavca.<br />(7) U ugovoru sklopljenom između posrednika i nalogodavca naročito moraju biti navedeni podaci o posredniku, broju pod kojim je upisan u Registar posrednika, nalogodavcu, vrsti i bitnome sadržaju posla za koji posrednik posreduje, o posredničkoj naknadi te o mogućim dodatnim tro&scaron;kovima koji nastanu kad posrednik u dogovoru sa nalogodavcem obavlja za njega i druge usluge u vezi sa poslom koji je predmet posredovanja.<br />(8) Ugovor o posredovanju može sadržavati i druge podatke u vezi sa poslom za koji se posreduje (npr. rok i uslove isplate posredničke naknade, podatke o osiguranju od odgovornosti, uslove osiguranja isplate posredničke naknade i sl.).</div>
                <p align="center"><br /><strong>Član 16.</strong><br /><strong>(Isključivo posredovanje)</strong></p>
                <div align="justify"><br />(1) Ugovorom o posredovanju nalogodavac se može obavezati da za posredovani posao neće angažovati drugog posrednika (isključivo posredovanje), koja obaveza mora biti izričito ugovorena.<br />(2) Ako je za vrijeme trajanja ugovora o isključivome posredovanju nalogodavac mimo posrednika sklopio pravni posao preko drugog posrednika,a za koji je isključivom posredniku bio dan nalog za posredovanje, dužan je isključivom posredniku platiti ugovorenu posredničku naknadu kao i moguće dodatne stvarne tro&scaron;kove učinjene tokom posredovanja za navedeni posredovani posao.<br />(3) Prilikom zaključivanja ugovora o isključivome posredovanju posrednik je dužan posebno upozoriti nalogodavca na značenje i pravne posljedice te klauzule.</div>
                <p align="center"><br /><strong>Član 17.</strong><br /><strong>(Prestanak ugovora o posredovanju)</strong></p>
                <div align="justify"><br />(1) Ugovor o posredovanju sklopljen na određeno vrijeme prestaje istekom roka na koji je sklopljen, zaključenjem pravnog posla za koji je posredovano ili otkazom bilo koje od ugovornih strana u pisanom obliku.<br />(2) Nalogodavac je dužan nadoknaditi posredniku učinjene tro&scaron;kove za koje je izričito ugovoreno da ih nalogodavac posebno plaća.&nbsp;<a href="https://advokat-prnjavorac.com/">https://advokat-prnjavorac.com</a><br />(3) Ako u roku od 12 mjeseci nakon prestanka ugovora o posredovanju nalogodavac sklopi pravni posao koji je posljedica posrednikova djelovanja prije prestanka ugovora o posredovanju, dužan je posredniku platiti posredničku naknadu u cijelosti, osim ako ugovorom nije drukčije ugovoreno.</div>
                <p align="center"><br /><strong>Član 18 .</strong><br /><strong>(Op&scaron;ti uslovi poslovanja)</strong></p>
                <div align="justify"><br />(1) Posrednik je obavezan utvrditi op&scaron;te uslove za obavljanje posredovanja (u daljnjem tekstu: op&scaron;ti uslovi poslovanja) u skladu s ovim zakonom i drugim propisima.<br />(2) Op&scaron;ti uslovi poslovanja moraju za svaku vrstu posredovanja sadržavati naročito:<br />a) opis poslova koje je posrednik obavezan obaviti pri obavljanju pojedinih radnji,<br />b) visinu posredničke naknade i opis poslova koji su obuhvaćeni tim plaćanjem, a koji obavezno obuhvaćaju dovođenje u vezu nalogodavca i trećeg lica i provjeravanje stanja nekretnina, potrebne pregovore i pripremne radnje za sklapanje pravnoga posla,<br />c) vrstu i iznos tro&scaron;kova, ako posrednik u dogovoru s nalogodavcem obavlja za njega i druge radnje u vezi sa poslom koji je predmet posredovanja.<br />(3) Posrednik je obavezan u svom poslovnom prostoru na vidljivu i pristupačnu mjestu istaknuti op&scaron;te uslove poslovanja.</div>
                <p align="center"><br /><strong>Član 19 .</strong><br /><strong>(Poslovni prostor)</strong></p>
                <div align="justify"><br />Posrednik mora poslovati u poslovnom prostoru primjerenom za kancelarijsko poslovanje koji je u cijelosti funkcionalno i fizički odvojen od prostora drugih namjena (stambeni, proizvodni, skladi&scaron;ni i sl.).</div>
                <p align="center"><br /><strong><strong>IV. PRAVA I OBAVEZE UGOVORNIH STRANA</strong></strong></p>
                <p align="center"><br /><strong>Član 20.</strong><br /><strong>(Pažnja u pravnome prometu)</strong></p>
                <div align="justify"><br />Posrednik u obavljanju poslova posredovanja, odnosno drugih radnji u vezi s poslom koji je predmet posredovanja mora postupati sa pažnjom dobrog privrednika, prema pravilima struke, poslovnoj etici i dobroj poslovnoj praksi.</div>
                <p align="center"><br /><strong>Član 21.</strong><br /><strong>(Ogla&scaron;avanje)</strong></p>
                <div align="justify"><br />(1) Posrednik je obavezan prilikom ogla&scaron;avanja u vezi sa prometom nekretnina koje su predmet posredovanja u sredstvima javnog informisanja, odnosno drugim pisanim i elektroničkim medijima, u svom poslovnom prostoru ili na drugim mjestima gdje je dozvoljeno ogla&scaron;avanje u vezi sa prometom nekretnina, objaviti svoju tvrtku i broj pod kojim je upisan u Registar posrednika, podatke o cijeni,ukoliko nije drugačije ugovoreno, lokaciji, povr&scaron;ini i strukturi nekretnine.<br />(2) Zabranjeno je ogla&scaron;avanje u vezi sa prometom nekretnine za čiji promet posrednik nema zaključen ugovor o posredovanju, odnosno ugovor o potposredovanju.</div>
                <p align="center"><br /><strong>Član 22.</strong><br /><strong>(Obaveze posrednika)</strong></p>
                <div align="justify"><br />Ugovorom o posredovanju posrednik se obavezuje obavljati naročito sljedeće:<br />a) nastojati naći i dovesti u vezu s nalogodavcem treće lice radi sklapanja posredovanoga posla,<br />b) dati nalogodavcu objektivno mi&scaron;ljenje o cijeni nekretnine ili iznosu zakupa u skladu sa njenim karakteristikama, prilikama na trži&scaron;tu i drugim relevantnim okolnostima,<br />c) pribaviti i izvr&scaron;iti uvid u isprave kojima se dokazuje vlasni&scaron;tvo ili drugo stvarno pravo na predmetnoj nekretnini,<br />d) obaviti potrebne radnje radi predstavljanja (prezentacije) nekretnine na trži&scaron;tu, oglasiti nekretninu na odgovarajući način te izvr&scaron;iti sve druge radnje dogovorene ugovorom o posredovanju koje prelaze uobičajenu prezentaciju, a za &scaron;to ima pravo na posebne, unaprijed iskazane tro&scaron;kove,<br />e) omogućiti pregled nekretnine,<br />f) posredovati u pregovorima i nastojati da dođe do sklapanja ugovora, ako se na to posebno obavezao,<br />g) čuvati lične podatke nalogodavca te po pisanome nalogu nalogodavca čuvati kao poslovnu tajnu podatke o nekretnini za koju posreduje ili u vezi s tom nekretninom ili s poslom za koji posreduje,<br />h) ako je predmet sklapanja ugovora zemlji&scaron;te, provjeriti namjenu predmetnog zemlji&scaron;ta,<br />i) obavijestiti nalogodavca o svim okolnostima važnim za namjeravani posao koje su mu poznate ili mu moraju biti poznate.</div>
                <p><br /><strong>Član 23.</strong><br /><strong>(Obaveze nalogodavca)</strong></p>
                <div align="justify"><br />(1) Ugovorom o posredovanju nalogodavac se obavezuje da će obaviti naročito sljedeće:<br />a) obavijestiti posrednika o svim okolnostima koje su važne za obavljanje posredovanja i predočiti tačne podatke o nekretnini te, ako posjeduje, dati posredniku na uvid lokacijsku, građevinsku, odnosno upotrebnu dozvolu za nekretninu koja je predmet ugovora, te dati na uvid posredniku dokaze o ispunjavanju obaveza vezanih za nekretninu,<br />b) dati posredniku na uvid isprave koje dokazuju njegovo vlasni&scaron;tvo na nekretnini, odnosno drugo stvarno pravo na nekretnini koja je predmet ugovora te upozoriti posrednika na sve uknjižene i neuknjižene terete koji postoje na nekretnini,<br />c) osigurati posredniku i trećem licu zainteresovanom za zaključivanje posredovanoga posla razgledanje nekretnine,<br />d) obavijestiti posrednika o svim bitnim podacima o nekretnini &scaron;to posebno uključuje opis nekretnine i cijenu,<br />e) nakon sklapanja posredovanoga pravnog posla, odnosno predugovora kojim se obavezao sklopiti posredovani pravni posao, ako su posrednik i nalogodavac ugovorili da se pravo na plaćanje posredničke naknade stječe već pri sklapanju predugovora, isplatiti posredniku posredničku naknadu, osim ako nije drukčije ugovoreno,<br />f) ako je to izričito ugovoreno nadoknaditi posredniku tro&scaron;kove učinjene tokom posredovanja koji prelaze uobičajene tro&scaron;kove posredovanja,<br />g) obavijestiti posrednika pisanim putem o svim promjenama u vezi s poslom za koji ga je ovlastio, a posebno o promjenama u vezi s vlasni&scaron;tvom na nekretnini.<br />(2) Nalogodavac nije dužan pristupiti pregovorima za sklapanje posredovanog posla s trećim licem kojeg je posrednik na&scaron;ao, niti sklopiti pravni posao, a odredba ugovora kojom je ugovoreno drukčije, ni&scaron;tavna je. Nalogodavac će posredniku odgovarati za &scaron;tetu, ako pri tom nije postupio u dobroj vjeri te je dužan nadoknaditi sve tro&scaron;kove učinjene tokom posredovanja, koji ne mogu biti manji od 1/3 niti veći od ugovorene posredničke naknade za posredovani posao.</div>
                <p><br /><strong>Član 24.</strong><br /><strong>(Anonimni nalogodavac)</strong></p>
                <br />(1) Posrednik koji poslove posredovanja obavlja za nalogodavca koji želi ostati anoniman, dužan je da ne otkriva identitet nalogodavca, u skladu sa uslovima iz ugovora o posredovanju, a najkasnije do zaključenja posredovanog pravnog posla.<br />(2) Klauzula o anonimnom nalogodavcu izričito se ugovara.
                <p><br /><strong>Član 25.</strong><br /><strong>(Ugovor o potposredovanju)</strong></p>
                <div align="justify"><br />(1) Posrednik može ugovorom o potposredovanju prenijeti svoja prava i obaveze iz ugovora o posredovanju, u cjelini ili djelomično, na drugog posrednika, ako se nalogodavac sa ovim izričito saglasio u ugovoru o posredovanju.<br />(2) Ugovor o potposredovanju zaključuje se u pisanom obliku i sadrži način i uslove prijenosa prava i obaveza iz stava (1) ovog člana, visinu i način isplate posredničke naknade i uslove za raskid ugovora.<br />(3) U slučaju iz stava (1) ovoga člana nalogodavac ostaje u ugovornome odnosu samo sa posrednikom s kojim je sklopio ugovor.<br />(4) Posrednik je dužan da kopiju ugovora iz stava (2) ovog člana preda nalogodavcu u roku od tri dana od dana zaključenja tog ugovora.</div>
                <p><br /><strong>Član 26.</strong><br /><strong>(Evidencija o posredovanju)</strong></p>
                <br />(1) Posrednik je dužan voditi evidenciju o posredovanju.<br />(2) Evidencija o posredovanju obavezno sadrži podatke o:<br />a) nalogodavcu i vrsti ugovora za čije sklapanje se posreduje,<br />b) vrsti nekretnine (zemlji&scaron;te s oznakom namjene kori&scaron;tenja, stambeni prostor, poslovni prostor i sl.),<br />c) lokaciji nekretnine,<br />d) tehničke podatke o nekretnini (sobnost, kvadratura i sl.),<br />e) cijeni u ukupnome iznosu i jediničnome iznosu za m2 povr&scaron;ine,<br />f) ishodu posredovanja i posredničkoj naknadi.<br />(3) Posrednik je dužan na zahtjev nadležnih organa uprave za potrebe trži&scaron;nog vrednovanja nekretnina i analize trži&scaron;ta nekretnina dati na uvid podatke iz evidencije o posredovanju.<br />(4) Oblik, sadržaj i način vođenja evidencije o posredovanju propisuje ministar.
                <p><br /><strong><strong>V. POSREDNIČKA NAKNADA</strong></strong></p>
                <p><br /><strong>Član 27.</strong><br /><strong>(Pravo na posredničku naknadu)</strong></p>
                <div align="justify"><br />(1) Visina posredničke naknade slobodno se određuje ugovorom o posredovanju.<br />(2) Posrednik stječe pravo na posredničku naknadu u momentu zaključenja ugovora za koji je posredovao, osim ako posrednik i nalogodavac nisu ugovorili da se pravo na posredničku naknade stječe u momentu zaključenja predugovora za koji je posrednik posredovao.<br />(3) Posrednik ne može zahtijevati djelomično plaćanje posredničke naknade unaprijed, odnosno prije zaključenja ugovora, odnosno predugovora u skladu sa stavom (2) ovoga člana.<br />(4) Tro&scaron;kove dodatnih usluga u vezi sa poslom koji je predmet posredovanja posrednik može naplatiti u visini stvarnih tro&scaron;kova ako je to izričito ugovoreno između posrednika i nalogodavca.<br />(5) Nakon prestanka ugovora posrednik ima pravo na posredničku naknadu u roku do 12 mjeseci, ako ugovorom nije drukčije ugovoreno, i u slučajevima kad nalogodavac sklopi sa trećim licem pravni posao koji je posljedica posrednikova djelovanja prije prestanka ugovora o posredovanju.<br />(6) Posrednik nema pravo na posredničku naknadu ako sa nalogodavcem u svoje ime, kao ugovorna strana zaključi ugovor koji je predmet posredovanja, odnosno ako takav ugovor sa nalogodavcem zaključi agent posredovanja koji za posrednika obavlja poslove posredovanja, u kojem slučaju posrednik ima pravo tražiti naknadu &scaron;tete od agenta posredovanja, u skladu sa propisima kojim se uređuju radni odnosi.<br />(7) Za izvr&scaron;enu uslugu posredovanja posrednik je dužan nalogodavcu ispostaviti fakturu i izdati fiskalni račun.</div>
                <p><br /><strong><strong>VI. NADZOR</strong></strong></p>
                <p><br /><strong>Član 28.</strong><br /><strong>(Upravni i inspekcijski nadzor)</strong></p>
                <br />(1) Upravni nadzor nad provođenjem ovog zakona i propisa donesenih na osnovu ovog zakona vr&scaron;i Ministarstvo.<br />(2) Inspekcijski nadzor nad provođenjem ovog zakona i propisa donesenih na osnovu ovog zakona vr&scaron;i Federalna uprava za inspekcijske poslove putem Federalnog trži&scaron;nog inspektorata i kantonalni organi nadležni za vr&scaron;enje inspekcijskog nadzora putem kantonalne trži&scaron;ne inspekcije, u skladu sa ovla&scaron;tenjima propisanim ovim zakonom i propisima kojima se uređuje inspekcijski nadzor.
                <p><br /><strong><strong>VII. KAZNENE ODREDBE</strong></strong></p>
                <p><br /><strong>Član 29.</strong></p>
                <br />Novčanom kaznom u iznosu od 2.000,00 do 10.000,00 KM kaznit će se za prekr&scaron;aj fizičko lice koje obavlja posredovanje suprotno odredbama ovog zakona (član 3. stav (2)).
                <p><br /><strong>Član 30.</strong></p>
                <br />(1) Novčanom kaznom u iznosu od 5.000,00 do 30.000,00 KM kaznit će se za prekr&scaron;aj pravno lice koje obavlja posredovanje a nije upisano u Registar posrednika (član 14. stav (1)).<br />(2) Za radnje iz stava (1) ovog člana kaznit će se fizičko lice registrovano za obavljanje djelatnosti posredovanja novčanom kaznom u iznosu od 2.500,00 KM do 15.000,00 KM.<br />(3) Za radnje iz stava (1) ovog člana kaznit će se za prekr&scaron;aj i odgovorno lice u pravnom licu novčanom kaznom u iznosu od 500,00 KM do 3.000,00 KM.<br />(4) Uz novčanu kaznu iz st. (1) i (2) ovog člana pravnom i fizičkom licu registrovanom za obavljanje djelatnosti posredovanja može se izreći i za&scaron;titna mjera zabrane obavljanja djelatnosti posredovanja, u trajanju od tri do &scaron;est mjeseci, kao i za&scaron;titna mjera javnog objavljivanja pravosnažno izrečene mjere zabrane.
                <p><br /><strong>Član 31.</strong></p>
                <br />(1) Novčanom kaznom u iznosu od 2.000,00 do 10.000,00 KM kaznit će se za prekr&scaron;aj pravno lice ako:<br />a) jednom godi&scaron;nje Ministarstvu ne dostavi ili blagovremeno ne dostavi dokumentaciju iz koje se može utvrditi da nisu prestali postojati zakonski uslovi za obavljanje posredovanja (član 6. stav (3)),<br />b) ne prijavi ili blagovremeno ne prijavi promjenu podataka ( član 10. stav (1)),<br />c) za poslove posredovanja zaposli ili van radnog odnosa angažuje lice koje nije upisano u Imenik agenata posredovanja (član 14. stav (2)),<br />d) obavlja posredovanje bez zaključenog ugovora o posredovanju (član 15. stav (3)),<br />e) ne upozori nalogodavca na značenje i posljedice klauzule o isključivom posredovanju (član 16. stav (3)),<br />f) ne utvrdi op&scaron;te uslove poslovanja i ne istakne ih na vidljivu mjestu (član 18. st. (1) i (3)),<br />g) posluje u poslovnom prostoru koji ne ispunjava propisane uslove (član 19.),<br />h) ako ogla&scaron;avanje obavlja u suprotnosti sa propisanim uslovima (član 21.),<br />i) ne vodi evidenciju o posredovanju ( član 26. st. (1) i (2)),<br />j) na zahtjev nadležnih organa uprave ne da na uvid podatke iz evidencije o posredovanju (član 26. stav (3)),<br />k) ostvari posredničku naknadu u suprotnosti sa propisanim uslovima ( član 27.)<br />(2) Za prekr&scaron;aj iz stava (1) ovog člana kaznit će se posrednik fizičko lice novčanom kaznom u iznosu od 1.000,00 do 5.000,00 KM.<br />(3) Za prekr&scaron;aj iz stava (1) ovog člana kaznit će se odgovorno lice u pravnom licu novčanom kaznom u iznosu od 300,00 do 1.000,00 KM.<br />(4) Uz novčanu kaznu iz stava (1) tač. c), d) i i) ovog člana, posredniku se može izreći i za&scaron;titna mjera zabrane obavljanja posredovanja u trajanju od tri do &scaron;est mjeseci.
                <p><br /><strong><strong>VIII. PRIJELAZNE I ZAVR&Scaron;NE ODREDBE</strong></strong></p>
                <p><br /><strong>Član 32.</strong></p>
                <br />(1) Podzakonske akte iz člana 7.stav (2), člana 13. st. (6) i (7) i člana 26. stav (4) ovog zakona donijet će ministar u roku od tri mjeseca od dana stupanja na snagu ovog zakona.<br />(2) Podzakonske akte iz člana 13. stav (8) ovog zakona donijet će Komora u roku od tri mjeseca od dana stupanja na snagu ovoga zakona.
                <p><br /><strong>Član 33.</strong></p>
                <div align="justify"><br />(1) Pravna i fizička lice koja na dan stupanja na snagu ovog zakona obavljaju djelatnost posredovanja na osnovu rje&scaron;enja o upisu u Registar poslovnih subjekata, odnosno na osnovu rje&scaron;enja nadležnog gradskog ili općinskog organa uprave dužna su uskladiti svoje poslovanje u skladu s odredbama ovog zakona u roku od 18 mjeseci od dana stupanja na snagu ovoga zakona.<br />(2) Pravnom i fizičkom licu iz stava (1) ovog člana koje ne uskladi svoje poslovanje s odredbama ovog zakona u roku iz stava (1) ovoga člana prestaje pravo na obavljanje djelatnosti posredovanja.</div>
                <p><br /><strong>Član 34.</strong><br /><strong>(Stupanje Zakona na snagu)</strong></p>
                <br />Ovaj Zakon stupa na snagu osmoga dana od dana objavljivanja u "Službenim novinama Federacije BIH".<br /><br /></div>
            <div>
                <p>Predsjedavajući<br />Predstavničkog doma<br />Parlamenta Federacije BiH<br /><strong>Mirsad Zaimović</strong>, s. r.</p>
            </div>
            <div>&nbsp;</div>
            <div>
                <p><br />Predsjedavajući<br />Doma naroda<br />Parlamenta Federacije BiH<br /><strong>Tomislav Martinović</strong>, s. r.</p>
            </div>
        </div>

    </div>

</template>
<script>
import {Component, Vue} from "nuxt-property-decorator";

@Component({
    layout: (ctx) => ctx.$device.isMobile ? 'mobile' : 'home',
})
export default class UsloviKoristenja extends Vue {

}
</script>
<style scoped>
@mixin for-phone-only {
    @media (max-width: 599px) {
        @content;
    }
}

.homepage-wrap {
    display: flex;
    flex-direction: column;
    width: 100%;
    box-sizing: border-box;
    background: #f9f9f9;
    margin-bottom: 64px;
    border-bottom: 1px solid #dcdcdc;
    max-width: 1300px;
    margin: 0 auto;
    margin-top: 80px;


    @include for-phone-only {
        padding: 0px;
        padding-bottom: 90px;
    }
}
</style>
